global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'forgemind-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'telemetry-simulator:8000'
          - 'telemetry-ingestion:8000'
          - 'anomaly-detection:8000'
          - 'rca-service:8000'
          - 'predictive-maintenance:8000'
          - 'ai-orchestrator:8000'
          - 'workflow-engine:8000'
          - 'chatops-service:8000'
          - 'reporting-service:8000'
          - 'notification-service:8000'
          - 'api-gateway:8000'
