<script setup>
import { ref, onMounted } from 'vue'
import { RCA } from '../composables/api'

const reports = ref([])
const selected = ref(null)

onMounted(async () => { reports.value = await RCA.list() })

function pickFirst(r) { if (!selected.value) selected.value = r }
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-semibold text-slate-100">AI RCA Reports</h1>
    <p class="text-sm text-slate-400">Generated by the Hermes RCA Agent · routed through the configured LLM API.</p>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div class="card lg:col-span-1 max-h-[70vh] overflow-y-auto">
        <h2 class="text-sm font-semibold uppercase tracking-wider text-slate-200 mb-3">Reports</h2>
        <ul class="space-y-2 text-sm">
          <li
            v-for="r in reports" :key="r.report_id"
            class="p-3 rounded-md cursor-pointer border border-transparent hover:border-accent-700 hover:bg-ink-700/40"
            :class="selected?.report_id === r.report_id ? 'bg-ink-700 border-accent-600' : ''"
            @click="selected = r; pickFirst(r)"
          >
            <div class="text-xs text-slate-500 font-mono">{{ new Date(r.generated_at).toLocaleString() }}</div>
            <div class="text-slate-100 font-medium truncate">{{ r.summary?.slice(0, 80) || '(no summary)' }}</div>
            <div class="mt-1 text-[10px] text-slate-400">conf {{ (r.confidence*100).toFixed(0) }}% · {{ r.model_used || '—' }}</div>
          </li>
          <li v-if="!reports.length" class="text-slate-500 text-sm italic">No reports yet — go to Incidents and run RCA.</li>
        </ul>
      </div>

      <div class="card lg:col-span-2" v-if="selected">
        <div class="flex items-center justify-between mb-3">
          <div>
            <div class="text-xs text-slate-500 font-mono">report {{ selected.report_id?.slice(0,8) }} · incident {{ selected.incident_id?.slice(0,8) }}</div>
            <div class="text-slate-100 text-lg mt-1">{{ selected.summary }}</div>
          </div>
          <div class="text-right">
            <div class="text-[10px] uppercase text-slate-500 tracking-wider">Confidence</div>
            <div class="font-mono text-xl text-accent-500">{{ (selected.confidence*100).toFixed(0) }}%</div>
          </div>
        </div>

        <div class="mt-4">
          <h3 class="text-xs uppercase tracking-wider text-slate-400 mb-2">Findings</h3>
          <div v-for="(f, idx) in selected.findings" :key="idx" class="card-tight mb-2 space-y-1">
            <div class="flex items-center justify-between">
              <span class="pill bg-accent-700/30 text-accent-500">{{ f.category }}</span>
              <span class="font-mono text-xs text-slate-400">L = {{ (f.likelihood*100).toFixed(0) }}%</span>
            </div>
            <div class="text-slate-100 text-sm">{{ f.hypothesis }}</div>
            <ul class="text-xs text-slate-400 list-disc list-inside">
              <li v-for="(ev, i) in f.evidence" :key="i">{{ ev }}</li>
            </ul>
          </div>
        </div>

        <div class="mt-4">
          <h3 class="text-xs uppercase tracking-wider text-slate-400 mb-2">Recommended actions</h3>
          <ul class="text-sm space-y-1">
            <li v-for="(a, i) in selected.recommended_actions" :key="i" class="bg-ink-700/40 rounded-md px-3 py-1.5">{{ a }}</li>
          </ul>
        </div>
      </div>

      <div class="card lg:col-span-2" v-else>
        <div class="text-slate-400 italic">Select a report to inspect.</div>
      </div>
    </div>
  </div>
</template>
